### ISSUE TITLE
Code for just training the centerpoint 

### ISSUE THREAD

**Issue by VikasRajashekar** [jvzonlab/OrganoidTracker#2]
Hi is it possible to jsut use the training of CNN part , given the input tiff images and the networks learn the centers?

**Comment by rutgerkok** [comment]
If you want to integrate the network into your codebase, then you can use the code included in https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:161642 . That contains the bare-bones Python code of the network, which you can adapt to work with whatever data format you use.

You can also still use the OrganoidTracker codebase, and then just ignore all the other functionality.
